import os, re
from lxml import etree

dirFiles = os.listdir('atual/')

for nome_arquivo in os.listdir('texto'):

    if nome_arquivo.endswith('.xml'):
        caminho_arquivo = os.path.join('texto', nome_arquivo)
        parser = etree.XMLParser()
        tree = etree.parse(caminho_arquivo, parser)
        root = tree.getroot()
        numero = root.find('.//meta/número').text
        nome = root.find('.//meta/nome').text

    f = open('html/' + numero + '.html','w+', encoding='utf-8')

    preHTML = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>Ruas de Braga</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="w3.css">
        <meta charset="utf-8"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-green">
                <h3>Rua: {nome}</h3>
            </header>
        </div>
    """

    posHTML = f"""
        <div>
            <footer class="w3-container w3-green">
                <h2>
                    <a href="index.html">
                    Voltar para a página principal</a>
                </h2>
                <h5>Generated by EMDApp::EngWeb2024::A96357</h5>
            </footer>
        </div>
    </body>
    </html>
    """

    conteudo = ""

    for para in root.findall('corpo/para'):
        text = ""
        for part in para.itertext():
            text += part.strip() + " "
        conteudo += "<p>{}</p>".format(text.strip())

    conteudo += "<div class='w3-container'><h2>Lista de Casas</h2><table class='w3-table w3-striped'>"
    conteudo += "<tr><th>Número</th><th>Enfiteuta</th><th>Foro</th><th>Descrição</th><th>Lugar</th></tr>"
    for casa in root.findall('corpo/lista-casas/casa'):
        numero = casa.find('número').text
        enfiteuta = casa.find('enfiteuta').text if casa.find('enfiteuta') is not None else "---"
        foro = casa.find('foro').text if casa.find('foro') is not None else "---"
        desc = ""
        if casa.find('desc/para') is not None:
            for part in casa.find('desc/para').itertext():
                desc += part.strip() + " "
        else:
            desc = "---"
        lugar = ""
        if casa.find('desc/para/lugar') is not None:
            lugar = casa.find('desc/para/lugar').text
        else:
            lugar = "---"

        conteudo += "<tr>"
        conteudo += "<td>{}</td>".format(numero)
        conteudo += "<td>{}</td>".format(enfiteuta)
        conteudo += "<td>{}</td>".format(foro)
        conteudo += "<td>{}</td>".format(desc)
        conteudo += "<td>{}</td>".format(lugar)
        conteudo += "</tr>"
        conteudo += "<tr><td colspan='5'><hr></td></tr>"

    conteudo += "</table>"



    
    '''
    conteudo += "<h2>Lista de Casas</h2>"
    conteudo += "<ul>"
    for casa in root.findall('corpo/lista-casas/casa'):
        numero = casa.find('número').text
        enfiteuta = casa.find('enfiteuta').text if casa.find('enfiteuta') is not None else ''
        foro = casa.find('foro').text if casa.find('foro') is not None else ''
        conteudo += "<li>Número: {} - Enfiteuta: {} - Foro: {}</li>".format(numero, enfiteuta, foro)
    conteudo += "</ul>"
    '''
    
    
    imagens_antigas = []
    imagens_novas = []
    legendas =[]
    
    for figura in root.findall('corpo/figura'):
        imagem = figura.find('imagem')
        imagens_antigas.append(imagem.get('path')[3:])
        legenda = figura.find('legenda')
        legendas.append(legenda.text)
     
    pattern = rf'^{numero}-.*$'
    imagens_novas = [file for file in dirFiles if re.match(pattern, file)]
    
    for img, legenda in zip(imagens_antigas, legendas):
        conteudo += f"""
            <div class="w3-container w3-teal">
                <h1>{nome}</h1>
                <figcaption>{legenda}</figcaption>
            </div>
            <img src="{'../' + img}" alt="{legenda}" style="width:100%">  
        """

    for img, legenda in zip(imagens_novas, legendas):
        conteudo += f"""
            <div class="w3-container w3-teal">
                <h1>{"nome"}</h1>
                <figcaption>{legenda}</figcaption>
            </div>
            <img src="{'../atual/' + img}" alt="{legenda}" style="width:100%">
        """

    f.write(preHTML + conteudo + posHTML)
print("Files created!")